github.anaplan.com:
    user: edward-andrewshodgson
    oauth_token: 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
    git_protocol: ssh
    users:
        edward-andrewshodgson:
            oauth_token: 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
